// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `starboard_entries` table.
    ///
    /// (Automatically generated by Diesel.)
    starboard_entries (id) {
        /// The `id` column of the `starboard_entries` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `guild_id` column of the `starboard_entries` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        guild_id -> Int8,
        /// The `channel_id` column of the `starboard_entries` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        channel_id -> Int8,
        /// The `message_id` column of the `starboard_entries` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        message_id -> Int8,
        /// The `reactions` column of the `starboard_entries` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        reactions -> Int4,
    }
}
